Traceback (most recent call last):
  File "/home/boris.grillborzer/PycharmProjects/PoseEstimationFPHAB/modelundmainfun.py", line 99, in <module>
    train()
  File "/home/boris.grillborzer/PycharmProjects/PoseEstimationFPHAB/modelundmainfun.py", line 81, in train
    out = model(data.x, data.edge_index, data.batch)  # Perform a single forward pass.
  File "/home/boris.grillborzer/miniconda3/envs/gggten/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/boris.grillborzer/miniconda3/envs/gggten/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/boris.grillborzer/PycharmProjects/PoseEstimationFPHAB/modelundmainfun.py", line 55, in forward
    x = self.conv1(x, edge_index)
  File "/home/boris.grillborzer/miniconda3/envs/gggten/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/boris.grillborzer/miniconda3/envs/gggten/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/boris.grillborzer/miniconda3/envs/gggten/lib/python3.10/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 242, in forward
    edge_index, edge_weight, x.size(self.node_dim),
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)